### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [MahmoudRH/D_Note#1]
Just wondering if you did already choose a license for your app? Without a license, it's "all rights reserved". Maybe you can pick a fitting license? [SPDX lists some](https://spdx.org/licenses/) and links to details. For true FOSS, please pick one that's approved by OSI/FSF. Thanks in advance!

**Comment by MahmoudRH** [comment]
License Added 😄

**Comment by IzzySoft** [comment]
Cool, thanks! I just prepared to have your app added to my repo. It should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.mahmoudrh.roomxml) around 6 pm UTC tomorrow. Updates will be fetched within 24h of your creating a new release and having the APK attached (with the `versionCode` increased, or users won't get an update notification – just mentioning this as it's often forgotten :wink:)

PS: If you like what you see there and want to link to it, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for visuals :smiley:
